"""AS11 RPC-surface name catalog.

Enumerations of valid RPC parameter values (variable names, spool
types, stream/event ids, etc.).

Contents:
    VAR_GROUPS                   Get/Set firmware-subtree-keyed var groups
    resolve_group/expand_groups  helpers for CLI --group expansion
    SPOOL_TYPES                  StartSpool valid spool_type values
    STREAM_DATA_IDS              StartStream valid data_ids
    EVENT_IDS                    SubscribeEvent valid event names
    VAR_NAMES                    [(long_name, short_tag), ...] every known var
    VAR_SUBTREES                 names that Get accepts as aggregate-subtree targets
    VAR_MODE_PREFIXES            human-friendly therapy-mode prefix groupings
    VAR_TOPIC_KEYWORDS           human-friendly topic substring groupings
    REGISTRIES                   {action: (data, description)} for `known`
    filter_vars/var_groups_summary/print_var_pairs   helpers for `known`

"""

from __future__ import annotations


VAR_GROUPS: dict[str, list[str]] = {
    "ConfigurationProfiles": [
        "DataMode",
        "ServiceHost",
        "ServicePort",
        "PeriodicBrokerContactPeriod",
        "UpgradeAbandonPeriod",
        "UpgradeReportPeriod",
        "OtaUpgradeStatus",
        "DataCollectAndSend",
        "DataCollectAndSendAsync",
        "DownloadBytesDelta",
        "UploadBytesDelta",
        "LastDataPostDateTime",
    ],
    "Network": [
        "AccessPointName",
    ],
    "DeviceConfiguration": [
        "FlightMode", "VALOTriggerSeconds",
        "RequestTestDriveState", "TestDrivePressure", "TestDriveType",
        "ExpiratoryPressure", "LearnTargetsExpiratoryPressure",
        "LearnTargetsPressureSupport", "LearnTargetsSetDuration",
        "HardwareIdentifier", "UniversalIdentifier", "SerialNumber",
        "ProductCode", "ProductName", "FdaUniqueDeviceIdentifier",
        "ProductGeographicIdentifier", "BootloaderIdentifier",
        "ApplicationIdentifier", "ConfigurationIdentifier",
        "PlatformIdentifier", "VariantIdentifier", "RegionIdentifier",
        "ProfileVariantIdentifier", "DataVersionIdentifier",
        "DataModelVersionIdentifier",
    ],
    "ManufacturingSettings": [
        "PhantomKey", "RequestLEDState", "CalibrationPressure",
        "SetMotorSpeed", "BluetoothPassthrough", "HumidifierPower",
        "HeatedTubePower", "RequestSDCardTest", "RequestLCDColour",
        "MotorFlowDrive", "MicrophoneEnabled", "SoundDownloadAllowed",
        "SoundcheckTestCount", "CALEnable",
        "MotorCurrent", "MotorSpeed", "AdcPressure",
        "AdcPressureMonitoring", "RawFlow",
        "RawAmbHumidity", "RawAmbTemperature", "RawAmbLight",
        "ButtonRegMap", "CurrentLEDState", "EndCapDetection",
        "LCDTouchStatus", "LCDConnector", "SDCardTestStatus",
        "SDCardSocketStatus", "IsReadyForShipping", "IsReadyForUpgrade",
        "IsFileSystemReady", "MotorType", "EraseMediaSignature",
        "SoundcheckStatus", "CALStatus", "SecurityStatus",
        "PressureGain", "PressureOffset", "FlowGain", "FlowOffset",
        "PressureMonitorGain", "PressureMonitorOffset",
        "LastTherapyUseDateTime", "LastEraseDataDateTime",
        "TherapyRunMeter", "MotorRunMeter",
        "MotorRunSinceLastServiceMeter", "MachineRunMeter",
        "LastMachineServiceDateTime",
        "AmbientHumidity-Estimated", "AmbientTemperature-Estimated",
        "AmbientLight", "FGState", "TestDriveState",
        "SystemError", "RecoverableError", "ActiveAlarms",
        "PowerSupplyType", "PowerSupplyCapacity", "TxLink2Connected",
        "HumidifierConnected", "TubeConnected",
        "BlowerFlow-100hz", "BlowerPressure-100hz",
        "HumidifierPlateCurrent", "HeatedTubeCurrent", "HumidifierPWM",
        "HumidifierPWMMinuteAverage", "HeatedTubePWM",
        "HeatedTubePWMMinuteAverage", "BlowerPressureMonitoring",
        "HumidifierPlateTemperature",
        "HumidifierPlateTemperatureMinuteAverage",
        "HeatedTubeOutletTemperature",
        "HeatedTubeOutletTemperatureMinuteAverage",

        "CalManufacturingMode", "DeviceIdStatus", "LearnMode",
        "CepstrumAverageCount", "CepstrumStartDelay",
        "CamlData", "ApplicationData", "PeripheralMsg",
        "OobxOnStartup", "PhantomTouch",
        "SettingsHistoryChangeCount", "StorageVersionId",
        "TOTAL_USED_HOURS_NAME",
    ],
    "TherapyProfile": [
        "ActiveTherapyProfile",
    ],
    "AlarmProfiles": [
        "AlarmVolumeLevel",
        "ApneaAlarmEnable", "ApneaAlarmThreshold",
        "HighLeakAlarmEnable",
        "LowMinuteVentAlarmEnable", "LowMinuteVentAlarmThreshold",
        "NonVentedMaskAlarmEnable",
    ],
    "FeatureProfiles": [
        # Ramp / AutoRamp / RampDown
        "MaxRampTime", "RampTime", "RampEnable", "RampEnablePatientAccess",
        "MaxRampDownTime", "RampDownTime", "RampDownEnable",
        "RampDownEnablePatientAccess",
        # Circuit
        "MaskType", "TubeType", "AntiBacterialFilter",
        # Climate / humidifier
        "ClimateControl", "HumidifierSettingEnable", "HumidifierLevel",
        "HeatedTubeSettingEnable", "HeatedTubeTemperature",
        "ExternalHumidifier",
        # Comfort
        "AutoSetComfort",
        # Confirm-stop
        "ConfirmStopEnable",
        # Care check
        "CareCheckToggle", "CareCheckInAvailable",
        # Device health / user solution
        "SoundcheckFeatureToggle", "SoundcheckRunFrequency",
        "ClinicalConfirmation", "MyAirScreens",
        # Display
        "TotalUsedHoursDisplayToggle", "SplashScreenDisplaySelection",
        "CycleDisplayFormat", "DisplayAHI",
        # EPR
        "EprEnablePatientAccess", "EprEnable", "EprType", "EprPressure",
        # Height
        "HeightDisplayUnit",
        # Language
        "LanguageConfiguration", "Language", "LanguageSelection",
        # Mask sense
        "MaskSenseToggle",
        # Patient view
        "PatientView",
        # Reminders
        "ReminderFilterEnable", "ReminderFilterDate", "ReminderFilterPeriod",
        "ReminderHumidifierEnable", "ReminderHumidifierDate",
        "ReminderHumidifierPeriod", "ReminderMaskEnable",
        "ReminderMaskDate", "ReminderMaskPeriod", "ReminderTubingEnable",
        "ReminderTubingDate", "ReminderTubingPeriod",
        # Smart start/stop
        "SmartStart", "SmartStop",
        # Temperature
        "TemperatureUnit",
        # Therapy LED
        "TherapyLEDAlwaysOn",
        # Time zone
        "TimeZoneOffset",
    ],
    "TherapyMode": [
        "ASVAuto-MinExpiratoryPressure", "ASVAuto-MaxExpiratoryPressure",
        "ASVAuto-StartPressure", "ASVAuto-MinPressureSupport",
        "ASVAuto-MaxPressureSupport", "ASV-TargetExpiratoryPressure",
        "ASV-MinPressureSupport", "ASV-MaxPressureSupport",
        "ASV-StartPressure", "HerAuto-MaxPressure", "HerAuto-MinPressure",
        "HerAuto-StartPressure", "AutoSet-MaxPressure",
        "AutoSet-MinPressure", "AutoSet-StartPressure", "Cpap-SetPressure",
        "Cpap-StartPressure", "Cpap-TriggerSensitivity",
        "PAC-TargetInspiratoryPressure", "PAC-TargetExpiratoryPressure",
        "PAC-StartPressure", "PAC-SetRespiratoryRate",
        "PAC-SetInspiratoryTime", "PAC-RiseTimeEnable", "PAC-RiseTime",
        "PAC-FallTimeEnable", "PAC-FallTime", "PAC-TriggerSensitivity",
        "ST-TargetInspiratoryPressure", "ST-TargetExpiratoryPressure",
        "ST-StartPressure", "ST-IntelligentBackupRateEnable",
        "ST-TargetRespiratoryRate", "ST-SetRespiratoryRate",
        "ST-SetMaxInspiratoryTime", "ST-SetMinInspiratoryTime",
        "ST-RiseTimeEnable", "ST-RiseTime", "ST-FallTimeEnable",
        "ST-FallTime", "ST-TriggerSensitivity", "ST-CycleSensitivity",
        "Spont-TargetInspiratoryPressure", "Spont-TargetExpiratoryPressure",
        "Spont-StartPressure", "Spont-RespiratoryRateEnable",
        "Spont-SetMaxInspiratoryTime", "Spont-SetMinInspiratoryTime",
        "Spont-EasyBreatheEnable", "Spont-RiseTimeEnable", "Spont-RiseTime",
        "Spont-FallTimeEnable", "Spont-FallTime",
        "Spont-TriggerSensitivity", "Spont-CycleSensitivity",
        "Timed-TargetInspiratoryPressure", "Timed-TargetExpiratoryPressure",
        "Timed-StartPressure", "Timed-SetRespiratoryRate",
        "Timed-SetInspiratoryTime", "Timed-RiseTimeEnable", "Timed-RiseTime",
        "Timed-FallTimeEnable", "Timed-FallTime",
        "VAuto-MaxInspiratoryPressure", "VAuto-MinExpiratoryPressure",
        "VAuto-StartPressure", "VAuto-SetMaxInspiratoryTime",
        "VAuto-SetMinInspiratoryTime", "VAuto-SetPressureSupport",
        "VAuto-TriggerSensitivity", "VAuto-CycleSensitivity",
        "iVAPS-PatientHeight", "iVAPS-AutoEPAPEnable",
        "iVAPS-MaxExpiratoryPressure", "iVAPS-MinExpiratoryPressure",
        "iVAPS-TargetExpiratoryPressure", "iVAPS-MinPressureSupport",
        "iVAPS-MaxPressureSupport", "iVAPS-StartPressure",
        "iVAPS-TargetAlveolarVentilation", "iVAPS-TargetRespiratoryRate",
        "iVAPS-SetMaxInspiratoryTime", "iVAPS-SetMinInspiratoryTime",
        "iVAPS-RiseTimeEnable", "iVAPS-RiseTime", "iVAPS-FallTimeEnable",
        "iVAPS-FallTime", "iVAPS-TriggerSensitivity",
        "iVAPS-CycleSensitivity",
    ],
    "CellularModule": [
        "CellularApplicationIdentifier",
        "CellularProductModel",
        "CellularProductProvider",
        "CellularDataPreamble",
        "IMEI",
        "IMSI",
        "SIMID",
    ],
    "BluetoothModule": [
        "BluetoothApplicationIdentifier",
        "BluetoothBootloaderIdentifier",
        "BluetoothName",
        "BluetoothPassthrough",
        "BluetoothProductModel",
        "BluetoothProductProvider",
    ],
    "TherapyMeasurements": [
        "RespiratoryEvent", "StatusEvent", "IsRamping", "TriggerCycleEvent",
        "IsRampingDown",
        "InspiratoryPressure", "ExpiratoryPressure", "RespiratoryRate",
        "HeartRate", "SpO2", "IeRatio", "Leak", "RawLeak",
        "MinuteVentilation", "TidalVolume", "AlveolarMinuteVentilation",
        "InspiratoryDuration", "ExpiratoryDuration",
        "TargetMinuteVentilation", "FlowLimitation", "SnoreIndex",
        "RemainingRampTime", "RemainingRampDownTime",
        "MaskPressure", "SetPressureWithoutCAD", "PatientFlow",
        "ExpirationSetPressure", "InspirationSetPressure", "CpapSetPressure",
    ],
}


def resolve_group(name: str) -> str | None:
    """Return canonical VAR_GROUPS key for `name`, or None if not present"""
    if name in VAR_GROUPS:
        return name
    lower_map = {k.lower(): k for k in VAR_GROUPS}
    return lower_map.get(name.lower())


def expand_groups(group_names: list[str]) -> list[str]:
    """Expand a list of --group arguments into the variable name list"""
    out: list[str] = []
    for g in group_names:
        canon = resolve_group(g)
        if canon is None:
            known = ", ".join(sorted(VAR_GROUPS))
            raise ValueError(f"unknown group {g!r}; known: {known}")
        out.extend(VAR_GROUPS[canon])
    return out



SPOOL_TYPES: list[str] = [
    # session & usage
    "Summary",
    "UsageEvents-TherapyStatusEvents",
    "TherapyEvents-RespiratoryEvents",
    "TherapyOneMinutePeriodic",
    "SettingProfilesCollection",
    "ConfigurationProfilesCollection",
    # system state / activity
    "SystemActivityEvents-FrequentActivityEvents",
    "SystemActivityEvents-SporadicActivityEvents",
    "SystemExceptionEvents-SystemErrors",
    "SystemExceptionEvents-RecoverableErrors",
    "SystemExceptionEvents-HumidifierErrors",
    "SystemExceptionEvents-HeatedTubeErrors",
    "DiagnosticExceptionEvents-AppErrors",
    "DiagnosticExceptionEvents-FatalErrors",
    "DiagnosticExceptionEvents-ResettableErrors",
    "DiagnosticExceptionEvents-AlarmAppErrors",
    "DiagnosticTenMinutePeriodic",
    # alarms
    "alarmEvents",
    "alarmDiagnosticEvents",
    # ui / survey / checks
    "GUIActivityEvents",
    "SurveyEvents",
    "SoundcheckVector",
    "AcousticSignatureV2",
    # metrics
    "MachineMetrics",
    "MemoryMetrics",
    "CellularActivityEvents",
    "CellularDataUsage",
    # high-rate / ambient signals
    "atmosphericPressure10min",
    "RespiratoryFlow6p25Hz",
    "MaskPressure6p25Hz",
    "InspiratoryPressure0p5Hz",
    "Leak0p5Hz",
]
STREAM_DATA_IDS = [
    "AmbientHumidity-Estimated", "AmbientTemperature-Estimated",
    "ApneaTreatmentPressure-50hz", "AutoSetTreatmentPressure-50hz",
    "BlowerFlow-100hz", "BlowerPressure-100hz", "BlowerPressure-OneMinute",
    "ExpiratoryPressure-50hz", "ExpiratoryPressure-TwoSecond",
    "FlowLimitation-50hz", "FlowLimitationTreatmentPressure-50hz",
    "InspiratoryPressure-50hz", "InspiratoryPressure-OneMinute",
    "InspiratoryPressure-TwoSecond",
    "Leak-50hz",
    "MaskPressure-100hz", "MaskPressure-OneMinute", "MaskPressure-TwoSecond",
    "MinuteVentilation-50hz", "PatientFlow-100hz",
    "RawLeak-50hz", "RemainingRampTime-50hz",
    "RespiratoryRate-50hz", "SetPressure-100hz",
    "SnoreIndex-50hz", "SnoreTreatmentPressure-50hz", "TidalVolume-50hz",
]

EVENT_IDS = [
    # mask / therapy lifecycle
    "MaskFitStart", "MaskFitStop", "MaskOn", "MaskOff",
    "MaskReminderAcknowledged",
    "PressureStart", "PressureStop",
    "RampDownStarted", "RampDownCompleted",
    # sensor / hardware anomalies
    "PressureStuckHigh", "PressureStuckLow", "PressureStuckMid",
    "PressureSensorDrift", "PressureSensorsPlausibility",
    "SensorFail",
    # alarm subsystem
    "AlarmImageRestored", "AlarmMuteState",
    "AlarmModuleCommunicationError", "AlarmSelfTestFailure",
    # upgrade lifecycle
    "AlarmUpgradeInitiated", "AlarmUpgradeSuccessful", "AlarmUpgradeFailed",
    "AlarmUpgradeFileTransferRequested",
    "AlarmUpgradeFileTransferCompleted", "AlarmUpgradeFileTransferFailed",
    "AlarmUpgradeFileSignatureMismatch",
    "UpgradePrepStarted",
    # device check
    "DeviceCheckInitiated", "DeviceCheckPassed", "DeviceCheckSystemError",
    "DeviceCheckNotificationDisplayed",
    # system errors
    "SystemErrorStarted",
    "SystemErrorCalibrationReset", "SystemErrorSettingsReset",
    "SystemErrorFastOverPressure", "SystemErrorSlowOverPressure",
    "SystemErrorOverTemperature", "SystemErrorOverVoltage",
    "SystemErrorImplausibleSupplyVoltage",
    "SystemErrorFaultyHWFaultDetectionCircuitry",
    "SystemErrorFlowSensorStuckHigh", "SystemErrorFlowSensorStuckLow",
    "SystemErrorNoFlowData",
    "SystemErrorPressureSensorDrift", "SystemErrorPressureSensorsPlausibility",
    "SystemErrorPressureStuckHigh", "SystemErrorPressureStuckLow",
    "SystemErrorPressureStuckMid",
    "SystemErrorMotorESD", "SystemErrorMotorFETs",
    "SystemErrorMotorHwFault", "SystemErrorMotorHwMitigationIC",
    "SystemErrorMotorStallHW", "SystemErrorMotorStallSW",
    "SystemErrorMotorSticky",
    # notifications observed on the wire
    "SpoolFragment",
]

# Names the device's `Get` RPC accepts as aggregate-subtree targets
# passing one of these returns the whole subtree in one call.
VAR_SUBTREES: frozenset[str] = frozenset({
    "ActiveProfiles",
    "AlarmProfiles",
    "ASVAutoProfile",
    "ASVProfile",
    "AutoRampFeature",
    "AutoSetForHerProfile",
    "AutoSetProfile",
    "CellularConfigurationProfiles",
    "CellularDataUsage",
    "CellularIdentificationProfiles",
    "CellularModule",
    "CircuitFeature",
    "ClimateFeature",
    "ComfortFeature",
    "ConfigurationProfiles",
    "CpapProfile",
    "DataDeliveryControl",
    "DeviceConfigurationSettings",
    "DeviceRegistration",
    "EprFeature",
    "FeatureProfiles",
    "IdentificationProfiles",
    "iVAPSProfile",
    "MachineMetrics",
    "PACProfile",
    "RampDownFeature",
    "SettingProfiles",
    "SmartStartStopFeature",
    "SpontProfile",
    "StoredDataDeliveryControl",
    "STProfile",
    "TherapyProfiles",
    "TimedProfile",
    "VAutoProfile",
})

# Short->path name map found in firmware (table at 0x08144cbc).
# NOT Get-able. Kept for documentation / future use.
VAR_PATH_ALIASES = {
    "alarmEvents":                                      "FlowGenerator.eventProfiles.alarmEvents",
    "alarmDiagnosticEvents":                            "FlowGenerator.eventProfiles.alarmDiagnosticEvents",
    "CellularBrokerURI":                                "CellularModule.ConfigurationProfiles.TherapySystemBrokerUniformResourceIdentifier",
    "CellularInternalModule":                           "CellularModule.IdentificationProfiles.CellularProfile.InternalModule",
    "CellularNetworkGeneration":                        "CellularModule.IdentificationProfiles.CellularProfile.Network.GenerationIdentifier",
    "CellularNetworkPlan":                              "CellularModule.IdentificationProfiles.CellularProfile.Network.PlanIdentifier",
    "CellularNetworkProvider":                          "CellularModule.IdentificationProfiles.CellularProfile.Network.ProviderIdentifier",
    "CellularNetworkProvisionedDateTime":               "CellularModule.IdentificationProfiles.CellularProfile.Network.ProvisionedDateTime",
    "CellularRegistrationURI":                          "CellularModule.ConfigurationProfiles.TherapySystemRegistrationUniformResourceIdentifier",
    "Diagnostic25HzPeriodic-BlowerFlow":                "FlowGenerator.MeasurementProfiles.Diagnostic25HzPeriodic.BlowerFlow",
    "Diagnostic25HzPeriodic-BlowerPressure":            "FlowGenerator.MeasurementProfiles.Diagnostic25HzPeriodic.BlowerPressure",
    "DiagnosticExceptionEvents-AlarmAppError":          "FlowGenerator.MeasurementProfiles.DiagnosticExceptionEvents.AlarmAppErrors.AlarmAppError",
    "DiagnosticExceptionEvents-AppError":               "FlowGenerator.MeasurementProfiles.DiagnosticExceptionEvents.AppErrors.AppError",
    "DiagnosticExceptionEvents-ErrorLogInfo":           "FlowGenerator.MeasurementProfiles.DiagnosticExceptionEvents.ErrorLogInfos.ErrorLogInfo",
    "DiagnosticExceptionEvents-FatalError":             "FlowGenerator.MeasurementProfiles.DiagnosticExceptionEvents.FatalErrors.FatalError",
    "DiagnosticExceptionEvents-ResettableError":        "FlowGenerator.MeasurementProfiles.DiagnosticExceptionEvents.ResettableErrors.ResettableError",
    "DiagnosticTenMinutePeriodic-CellularSignalQuality2G":   "FlowGenerator.MeasurementProfiles.DiagnosticTenMinutePeriodic.CellularSignalQuality2G",
    "DiagnosticTenMinutePeriodic-CellularSignalQuality3G":   "FlowGenerator.MeasurementProfiles.DiagnosticTenMinutePeriodic.CellularSignalQuality3G",
    "DiagnosticTenMinutePeriodic-CellularSignalQualityLTE":  "FlowGenerator.MeasurementProfiles.DiagnosticTenMinutePeriodic.CellularSignalQualityLTE",
    "DiagnosticTenMinutePeriodic-CellularSignalStrength":    "FlowGenerator.MeasurementProfiles.DiagnosticTenMinutePeriodic.CellularSignalStrength",
    "Summary":                                          "FlowGenerator.MeasurementProfiles.Summary",
    "SystemActivityEvents-FrequentActivityEvent":       "FlowGenerator.MeasurementProfiles.SystemActivityEvents.FrequentActivityEvents.FrequentActivityEvent",
    "SystemActivityEvents-SporadicActivityEvent":       "FlowGenerator.MeasurementProfiles.SystemActivityEvents.SporadicActivityEvents.SporadicActivityEvent",
    "SystemExceptionEvents-HeatedTubeError":            "FlowGenerator.MeasurementProfiles.SystemExceptionEvents.HeatedTubeErrors.HeatedTubeError",
    "SystemExceptionEvents-HumidifierError":            "FlowGenerator.MeasurementProfiles.SystemExceptionEvents.HumidifierErrors.HumidifierError",
    "SystemExceptionEvents-RecoverableError":           "FlowGenerator.MeasurementProfiles.SystemExceptionEvents.RecoverableErrors.RecoverableError",
    "SystemExceptionEvents-SystemError":                "FlowGenerator.MeasurementProfiles.SystemExceptionEvents.SystemErrors.SystemError",
    "TherapyEvents-RespiratoryEvent":                   "FlowGenerator.MeasurementProfiles.TherapyEvents.RespiratoryEvents.RespiratoryEvent",
    "TherapyOneHzPeriodic-HeartRate":                   "FlowGenerator.MeasurementProfiles.TherapyOneHzPeriodic.HeartRate",
    "TherapyOneHzPeriodic-SpO2":                        "FlowGenerator.MeasurementProfiles.TherapyOneHzPeriodic.SpO2",
    "TherapyOneMinutePeriodic-AlveolarMinuteVentilation": "FlowGenerator.MeasurementProfiles.TherapyOneMinutePeriodic.AlveolarMinuteVentilation",
    "TherapyOneMinutePeriodic-ExpiratoryPressure":      "FlowGenerator.MeasurementProfiles.TherapyOneMinutePeriodic.ExpiratoryPressure",
    "TherapyOneMinutePeriodic-HeartRate":               "FlowGenerator.MeasurementProfiles.TherapyOneMinutePeriodic.HeartRate",
    "TherapyOneMinutePeriodic-IeRatio":                 "FlowGenerator.MeasurementProfiles.TherapyOneMinutePeriodic.IeRatio",
    "TherapyOneMinutePeriodic-InspiratoryDuration":     "FlowGenerator.MeasurementProfiles.TherapyOneMinutePeriodic.InspiratoryDuration",
    "TherapyOneMinutePeriodic-InspiratoryPressure":     "FlowGenerator.MeasurementProfiles.TherapyOneMinutePeriodic.InspiratoryPressure",
    "TherapyOneMinutePeriodic-Leak":                    "FlowGenerator.MeasurementProfiles.TherapyOneMinutePeriodic.Leak",
    "TherapyOneMinutePeriodic-MinuteVentilation":       "FlowGenerator.MeasurementProfiles.TherapyOneMinutePeriodic.MinuteVentilation",
    "TherapyOneMinutePeriodic-RespiratoryRate":         "FlowGenerator.MeasurementProfiles.TherapyOneMinutePeriodic.RespiratoryRate",
    "TherapyOneMinutePeriodic-SpO2":                    "FlowGenerator.MeasurementProfiles.TherapyOneMinutePeriodic.SpO2",
    "TherapyOneMinutePeriodic-TidalVolume":             "FlowGenerator.MeasurementProfiles.TherapyOneMinutePeriodic.TidalVolume",
    "TherapyTwentyFiveHzPeriodic-MaskPressure":         "FlowGenerator.MeasurementProfiles.TherapyTwentyFiveHzPeriodic.MaskPressure",
    "TherapyTwentyFiveHzPeriodic-RespiratoryFlow":      "FlowGenerator.MeasurementProfiles.TherapyTwentyFiveHzPeriodic.RespiratoryFlow",
    "TherapyTwoSecondPeriodic-ExpiratoryPressure":      "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.ExpiratoryPressure",
    "TherapyTwoSecondPeriodic-FlowLimitation":          "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.FlowLimitation",
    "TherapyTwoSecondPeriodic-IeRatio":                 "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.IeRatio",
    "TherapyTwoSecondPeriodic-InspiratoryDuration":     "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.InspiratoryDuration",
    "TherapyTwoSecondPeriodic-InspiratoryPressure":     "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.InspiratoryPressure",
    "TherapyTwoSecondPeriodic-Leak":                    "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.Leak",
    "TherapyTwoSecondPeriodic-MaskPressure":            "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.MaskPressure",
    "TherapyTwoSecondPeriodic-MinuteVentilation":       "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.MinuteVentilation",
    "TherapyTwoSecondPeriodic-RespiratoryRate":         "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.RespiratoryRate",
    "TherapyTwoSecondPeriodic-SnoreIndex":              "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.SnoreIndex",
    "TherapyTwoSecondPeriodic-TargetMinuteVentilation": "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.TargetMinuteVentilation",
    "TherapyTwoSecondPeriodic-TidalVolume":             "FlowGenerator.MeasurementProfiles.TherapyTwoSecondPeriodic.TidalVolume",
    "UsageEvents-TherapyStatusEvent":                   "FlowGenerator.MeasurementProfiles.UsageEvents.TherapyStatusEvents.TherapyStatusEvent",
}


VAR_NAMES = [
    ("ASV-MaxPressureSupport", "XC2"),
    ("ASV-MinPressureSupport", "XC3"),
    ("ASV-StartPressure", "XC0"),
    ("ASV-TargetExpiratoryPressure", "XC1"),
    ("ASVAuto-MaxExpiratoryPressure", "XD1"),
    ("ASVAuto-MaxPressureSupport", "XD3"),
    ("ASVAuto-MinExpiratoryPressure", "XD2"),
    ("ASVAuto-MinPressureSupport", "XD4"),
    ("ASVAuto-StartPressure", "XD0"),
    ("AccessPointName", "CLA"),
    ("ActiveAlarms", "AER"),
    ("ActiveTherapyProfile", "MOP"),
    ("AdcPressure", "PRS"),
    ("AdcPressureMonitoring", "PR2"),
    ("AlarmVolumeLevel", "AVQ"),
    ("AlveolarMinuteVentilation", "AAV"),
    ("AmbientHumidity-Estimated", "ABH"),
    ("AmbientLight", "ALS"),
    ("AmbientTemperature-Estimated", "HAT"),
    ("AntiBacterialFilter", "ABF"),
    ("ApneaAlarmEnable", "ANC"),
    ("ApneaAlarmThreshold", "APV"),
    ("ApneaTreatmentPressure-50hz", "AP5"),
    ("ApplicationData", "MAD"),
    ("ApplicationIdentifier", "SID"),
    ("AutoSet-MaxPressure", "MPA"),
    ("AutoSet-MinPressure", "MPI"),
    ("AutoSet-StartPressure", "STU"),
    ("AutoSetComfort", "AFC"),
    ("AutoSetTreatmentPressure-50hz", "AT5"),
    ("BlowerFlow-100hz", "BFT"),
    ("BlowerPressure-100hz", "BPT"),
    ("BlowerPressure-OneMinute", "BPA"),
    ("BlowerPressureMonitoring", "BPS"),
    ("BluetoothApplicationIdentifier", "BTV"),
    ("BluetoothBootloaderIdentifier", "BBV"),
    ("BluetoothName", "BTN"),
    ("BluetoothPassthrough", "BNP"),
    ("BluetoothProductModel", "BPM"),
    ("BluetoothProductProvider", "BPP"),
    ("BootloaderIdentifier", "BID"),
    ("ButtonRegMap", "KPT"),
    ("CALEnable", "MEN"),
    ("CALStatus", "CST"),
    ("CalManufacturingMode", "CMM"),
    ("CalibrationPressure", "CPR"),
    ("CamlData", "CMD"),
    ("CareCheckInAvailable", "CCA"),
    ("CareCheckToggle", "MAI"),
    ("CellularApplicationIdentifier", "CSI"),
    ("CellularDataPreamble", "CDP"),
    ("CellularProductModel", "CPM"),
    ("CellularProductProvider", "CPP"),
    ("CepstrumAverageCount", "EIC"),
    ("CepstrumStartDelay", "EST"),
    ("ClimateControl", "CCO"),
    ("ClinicalConfirmation", "CFC"),
    ("ConfigurationIdentifier", "CID"),
    ("ConfirmStopEnable", "SCF"),
    ("Cpap-SetPressure", "IPC"),
    ("Cpap-StartPressure", "STP"),
    ("Cpap-TriggerSensitivity", "C11"),
    ("CpapSetPressure", "CSP"),
    ("CurrentLEDState", "CLS"),
    ("CycleDisplayFormat", "SSY"),
    ("DataCollectAndSend", "DSS"),
    ("DataCollectAndSendAsync", "ADS"),
    ("DataMode", "CDM"),
    ("DataModelVersionIdentifier", "DMV"),
    ("DataVersionIdentifier", "PVD"),
    ("DeviceIdStatus", "DIS"),
    ("DisplayAHI", "DAH"),
    ("DownloadBytesDelta", "DDD"),
    ("EndCapDetection", "ECD"),
    ("EprEnable", "EPX"),
    ("EprEnablePatientAccess", "EPA"),
    ("EprPressure", "EPR"),
    ("EprType", "EPT"),
    ("EraseMediaSignature", "EMS"),
    ("ExpirationSetPressure", "ESP"),
    ("ExpiratoryDuration", "EXT"),
    ("ExpiratoryPressure", "EXP"),
    ("ExpiratoryPressure-50hz", "EP5"),
    ("ExpiratoryPressure-TwoSecond", "MKE"),
    ("ExternalHumidifier", "EXH"),
    ("FGState", "ZRM"),
    ("FdaUniqueDeviceIdentifier", "UDI"),
    ("FlightMode", "QFC"),
    ("FlowGain", "FLG"),
    ("FlowLimitation", "FFL"),
    ("FlowLimitation-50hz", "FF5"),
    ("FlowLimitationTreatmentPressure-50hz", "FL5"),
    ("FlowOffset", "FLZ"),
    ("HardwareIdentifier", "PCB"),
    ("HeartRate", "HRT"),
    ("HeatedTubeCurrent", "HTL"),
    ("HeatedTubeOutletTemperature", "HTT"),
    ("HeatedTubeOutletTemperatureMinuteAverage", "HTA"),
    ("HeatedTubePWM", "HBP"),
    ("HeatedTubePWMMinuteAverage", "ABP"),
    ("HeatedTubePower", "HTP"),
    ("HeatedTubeSettingEnable", "HTX"),
    ("HeatedTubeTemperature", "HTS"),
    ("HeightDisplayUnit", "IHU"),
    ("HerAuto-MaxPressure", "HMA"),
    ("HerAuto-MinPressure", "HMI"),
    ("HerAuto-StartPressure", "HSP"),
    ("HighLeakAlarmEnable", "HLA"),
    ("HumidifierConnected", "HCR"),
    ("HumidifierLevel", "HMS"),
    ("HumidifierPWM", "HUP"),
    ("HumidifierPWMMinuteAverage", "AHP"),
    ("HumidifierPlateCurrent", "HCL"),
    ("HumidifierPlateTemperature", "HPT"),
    ("HumidifierPlateTemperatureMinuteAverage", "HHT"),
    ("HumidifierPower", "HPW"),
    ("HumidifierSettingEnable", "HMX"),
    ("IMEI", "CIE"),
    ("IMSI", "CIM"),
    ("IeRatio", "IET"),
    ("InspirationSetPressure", "ISP"),
    ("InspiratoryDuration", "INT"),
    ("InspiratoryPressure", "INP"),
    ("InspiratoryPressure-50hz", "INH"),
    ("InspiratoryPressure-OneMinute", "AIP"),
    ("InspiratoryPressure-TwoSecond", "MKI"),
    ("IsFileSystemReady", "IRF"),
    ("IsRamping", "ZRP"),
    ("IsRampingDown", "RPD"),
    ("IsReadyForShipping", "IRS"),
    ("IsReadyForUpgrade", "IRU"),
    ("LCDConnector", "LCS"),
    ("LCDTouchStatus", "LTS"),
    ("Language", "LAN"),
    ("LanguageConfiguration", "LNC"),
    ("LanguageSelection", "SLS"),
    ("LastDataPostDateTime", "LDT"),
    ("LastEraseDataDateTime", "CED"),
    ("LastMachineServiceDateTime", "LMS"),
    ("LastTherapyUseDateTime", "CUD"),
    ("Leak", "LKF"),
    ("Leak-50hz", "LK5"),
    ("LearnMode", "TLM"),
    ("LearnTargetsExpiratoryPressure", "ZIE"),
    ("LearnTargetsPressureSupport", "ZLP"),
    ("LearnTargetsSetDuration", "ZIC"),
    ("LowMinuteVentAlarmEnable", "LMC"),
    ("LowMinuteVentAlarmThreshold", "LMT"),
    ("MachineRunMeter", "MHU"),
    ("MaskPressure", "MKP"),
    ("MaskPressure-100hz", "MK1"),
    ("MaskPressure-OneMinute", "MAP"),
    ("MaskPressure-TwoSecond", "MKF"),
    ("MaskSenseToggle", "MKD"),
    ("MaskType", "MSK"),
    ("MaxRampDownTime", "MRD"),
    ("MaxRampTime", "MRT"),
    ("MicrophoneEnabled", "MIC"),
    ("MinuteVentilation", "MV6"),
    ("MinuteVentilation-50hz", "MVH"),
    ("MotorCurrent", "CUR"),
    ("MotorFlowDrive", "CFL"),
    ("MotorRunMeter", "MHR"),
    ("MotorRunSinceLastServiceMeter", "MHS"),
    ("MotorSpeed", "SPD"),
    ("MotorType", "BMT"),
    ("MyAirScreens", "MAS"),
    ("NonVentedMaskAlarmEnable", "NMA"),
    ("OobxOnStartup", "SOS"),
    ("OtaUpgradeStatus", "OUS"),
    ("PAC-FallTime", "P12"),
    ("PAC-FallTimeEnable", "P11"),
    ("PAC-RiseTime", "PA4"),
    ("PAC-RiseTimeEnable", "PA3"),
    ("PAC-SetInspiratoryTime", "PA5"),
    ("PAC-SetRespiratoryRate", "PA6"),
    ("PAC-StartPressure", "PA0"),
    ("PAC-TargetExpiratoryPressure", "PA2"),
    ("PAC-TargetInspiratoryPressure", "PA1"),
    ("PAC-TriggerSensitivity", "PA7"),
    ("PatientFlow", "RFL"),
    ("PatientFlow-100hz", "RF5"),
    ("PatientView", "ACC"),
    ("PeriodicBrokerContactPeriod", "BCP"),
    ("PeripheralMsg", "PMS"),
    ("PhantomKey", "KEY"),
    ("PhantomTouch", "TCH"),
    ("PlatformIdentifier", "MID"),
    ("PowerSupplyCapacity", "PSC"),
    ("PowerSupplyType", "PSU"),
    ("PressureGain", "PSH"),
    ("PressureMonitorGain", "PS1"),
    ("PressureMonitorOffset", "PZ1"),
    ("PressureOffset", "PZH"),
    ("ProductCode", "PCD"),
    ("ProductGeographicIdentifier", "PGI"),
    ("ProductName", "PNA"),
    ("ProfileVariantIdentifier", "PVI"),
    ("RampDownEnable", "RDE"),
    ("RampDownEnablePatientAccess", "DPE"),
    ("RampDownTime", "SRT"),
    ("RampEnable", "RMA"),
    ("RampEnablePatientAccess", "RPE"),
    ("RampTime", "RMT"),
    ("RawAmbHumidity", "AHR"),
    ("RawAmbLight", "RAL"),
    ("RawAmbTemperature", "ATR"),
    ("RawFlow", "FLW"),
    ("RawLeak", "SFK"),
    ("RawLeak-50hz", "SF5"),
    ("RecoverableError", "RYS"),
    ("RegionIdentifier", "RID"),
    ("RemainingRampDownTime", "RDD"),
    ("RemainingRampTime", "ZRC"),
    ("RemainingRampTime-50hz", "ZR5"),
    ("ReminderFilterDate", "RTF"),
    ("ReminderFilterEnable", "RIF"),
    ("ReminderFilterPeriod", "RDF"),
    ("ReminderHumidifierDate", "RTH"),
    ("ReminderHumidifierEnable", "RIC"),
    ("ReminderHumidifierPeriod", "RDH"),
    ("ReminderMaskDate", "RTM"),
    ("ReminderMaskEnable", "RIM"),
    ("ReminderMaskPeriod", "RDM"),
    ("ReminderTubingDate", "RTT"),
    ("ReminderTubingEnable", "RIT"),
    ("ReminderTubingPeriod", "RDT"),
    ("RequestLCDColour", "RLC"),
    ("RequestLEDState", "RLS"),
    ("RequestSDCardTest", "RST"),
    ("RequestTestDriveState", "RTS"),
    ("RespiratoryEvent", "AET"),
    ("RespiratoryRate", "RR6"),
    ("RespiratoryRate-50hz", "RR5"),
    ("SDCardSocketStatus", "SSS"),
    ("SDCardTestStatus", "STS"),
    ("SIMID", "CCD"),
    ("ST-CycleSensitivity", "XAB"),
    ("ST-FallTime", "XAP"),
    ("ST-FallTimeEnable", "XAM"),
    ("ST-IntelligentBackupRateEnable", "XAC"),
    ("ST-RiseTime", "XAA"),
    ("ST-RiseTimeEnable", "XA9"),
    ("ST-SetMaxInspiratoryTime", "XA7"),
    ("ST-SetMinInspiratoryTime", "XA8"),
    ("ST-SetRespiratoryRate", "XA6"),
    ("ST-StartPressure", "XA3"),
    ("ST-TargetExpiratoryPressure", "XA2"),
    ("ST-TargetInspiratoryPressure", "XA1"),
    ("ST-TargetRespiratoryRate", "XAD"),
    ("ST-TriggerSensitivity", "ZU1"),
    ("SecurityStatus", "SBE"),
    ("SerialNumber", "SRN"),
    ("ServiceHost", "CLU"),
    ("ServicePort", "CLP"),
    ("SetMotorSpeed", "SSD"),
    ("SetPressure-100hz", "SPH"),
    ("SetPressureWithoutCAD", "OPP"),
    ("SettingsHistoryChangeCount", "SHC"),
    ("SmartStart", "SST"),
    ("SmartStop", "SSP"),
    ("SnoreIndex", "SNI"),
    ("SnoreIndex-50hz", "SN5"),
    ("SnoreTreatmentPressure-50hz", "SR5"),
    ("SoundDownloadAllowed", "DSA"),
    ("SoundcheckFeatureToggle", "SCO"),
    ("SoundcheckRunFrequency", "SCK"),
    ("SoundcheckStatus", "STT"),
    ("SoundcheckTestCount", "SSC"),
    ("SpO2", "SAO"),
    ("SplashScreenDisplaySelection", "SSE"),
    ("Spont-CycleSensitivity", "Z12"),
    ("Spont-EasyBreatheEnable", "ZZ4"),
    ("Spont-FallTime", "Z17"),
    ("Spont-FallTimeEnable", "Z16"),
    ("Spont-RespiratoryRateEnable", "ZZ5"),
    ("Spont-RiseTime", "Z10"),
    ("Spont-RiseTimeEnable", "ZZ9"),
    ("Spont-SetMaxInspiratoryTime", "ZZ7"),
    ("Spont-SetMinInspiratoryTime", "ZZ8"),
    ("Spont-StartPressure", "ZZ3"),
    ("Spont-TargetExpiratoryPressure", "ZZ2"),
    ("Spont-TargetInspiratoryPressure", "ZZ1"),
    ("Spont-TriggerSensitivity", "Z11"),
    ("StatusEvent", "THS"),
    ("StorageVersionId", "SVD"),
    ("Summary-AmbientHumidity-50", "AUM"),
    ("Summary-ApneaHypopneaIndex", "AHI"),
    ("Summary-ApneaIndex", "ASC"),
    ("Summary-BlowerFlow-50", "BFM"),
    ("Summary-BlowerPressure-5", "BP5"),
    ("Summary-BlowerPressure-95", "BP9"),
    ("Summary-CentralApneaIndex", "OSC"),
    ("Summary-ExpiratoryPressure-100", "PEA"),
    ("Summary-ExpiratoryPressure-50", "PEM"),
    ("Summary-ExpiratoryPressure-95", "PE9"),
    ("Summary-HeartRate-100", "HRX"),
    ("Summary-HeartRate-50", "HRM"),
    ("Summary-HeartRate-95", "HR9"),
    ("Summary-HeatedTubePower-50", "AHM"),
    ("Summary-HeatedTubeTemperature-50", "HTE"),
    ("Summary-HumidifierConnected", "HUC"),
    ("Summary-HumidifierPower-50", "APM"),
    ("Summary-HumidifierTemperature-50", "HHE"),
    ("Summary-HypopneaIndex", "HSC"),
    ("Summary-IeRatio-100", "IEA"),
    ("Summary-IeRatio-50", "IEM"),
    ("Summary-IeRatio-95", "IE9"),
    ("Summary-InspiratoryDuration-100", "ISA"),
    ("Summary-InspiratoryDuration-50", "ISM"),
    ("Summary-InspiratoryDuration-95", "IS9"),
    ("Summary-InspiratoryPressure-100", "PIA"),
    ("Summary-InspiratoryPressure-50", "PIM"),
    ("Summary-InspiratoryPressure-95", "PI9"),
    ("Summary-Leak-100", "LMX"),
    ("Summary-Leak-50", "LKM"),
    ("Summary-Leak-75", "LK7"),
    ("Summary-Leak-95", "LK9"),
    ("Summary-MeanMaskPressure-100", "PMA"),
    ("Summary-MeanMaskPressure-50", "MSP"),
    ("Summary-MeanMaskPressure-95", "PM9"),
    ("Summary-MinuteVentilation-100", "VTA"),
    ("Summary-MinuteVentilation-50", "VTM"),
    ("Summary-MinuteVentilation-95", "VT9"),
    ("Summary-ObstructiveApneaIndex", "CSC"),
    ("Summary-ReraIndex", "RCC"),
    ("Summary-RespiratoryFlow-5", "RFM"),
    ("Summary-RespiratoryFlow-95", "R95"),
    ("Summary-RespiratoryRate-100", "RRA"),
    ("Summary-RespiratoryRate-50", "RRM"),
    ("Summary-RespiratoryRate-95", "RR9"),
    ("Summary-SpO2-100", "SOX"),
    ("Summary-SpO2-50", "SOM"),
    ("Summary-SpO2-95", "SO9"),
    ("Summary-SpontCyclePercentage", "VCR"),
    ("Summary-SpontTriggerPercentage", "VSR"),
    ("Summary-TargetMinuteVentilation-100", "VAA"),
    ("Summary-TargetMinuteVentilation-50", "VAM"),
    ("Summary-TargetMinuteVentilation-95", "VA9"),
    ("Summary-TidalVolume-100", "TVA"),
    ("Summary-TidalVolume-50", "TVM"),
    ("Summary-TidalVolume-95", "TV9"),
    ("Summary-TubeConnected", "ZHT"),
    ("Summary-UnknownApneaIndex", "USC"),
    ("SystemError", "FSE"),
    ("TOTAL_USED_HOURS_NAME", "PHR"),
    ("TargetMinuteVentilation", "TVP"),
    ("TemperatureUnit", "TMU"),
    ("TestDrivePressure", "TDP"),
    ("TestDriveState", "TDS"),
    ("TestDriveType", "TDT"),
    ("TherapyLEDAlwaysOn", "TLF"),
    ("TherapyRunMeter", "PHM"),
    ("TidalVolume", "TID"),
    ("TidalVolume-50hz", "TI5"),
    ("TimeZoneOffset", "TZO"),
    ("Timed-FallTime", "XBA"),
    ("Timed-FallTimeEnable", "XB9"),
    ("Timed-RiseTime", "XB7"),
    ("Timed-RiseTimeEnable", "XB6"),
    ("Timed-SetInspiratoryTime", "XB5"),
    ("Timed-SetRespiratoryRate", "XB4"),
    ("Timed-StartPressure", "XB0"),
    ("Timed-TargetExpiratoryPressure", "XB2"),
    ("Timed-TargetInspiratoryPressure", "XB1"),
    ("TotalUsedHoursDisplayToggle", "TUD"),
    ("TriggerCycleEvent", "BTE"),
    ("TubeConnected", "ZHR"),
    ("TubeType", "TBT"),
    ("TxLink2Connected", "TXC"),
    ("UniversalIdentifier", "GUD"),
    ("UpgradeAbandonPeriod", "OAP"),
    ("UpgradeReportPeriod", "ORP"),
    ("UploadBytesDelta", "DUD"),
    ("VALOTriggerSeconds", "VTD"),
    ("VAuto-CycleSensitivity", "XE7"),
    ("VAuto-MaxInspiratoryPressure", "XE1"),
    ("VAuto-MinExpiratoryPressure", "XE2"),
    ("VAuto-SetMaxInspiratoryTime", "XE4"),
    ("VAuto-SetMinInspiratoryTime", "XE5"),
    ("VAuto-SetPressureSupport", "XE3"),
    ("VAuto-StartPressure", "XE0"),
    ("VAuto-TriggerSensitivity", "XE6"),
    ("VariantIdentifier", "VID"),
    ("iVAPS-AutoEPAPEnable", "IEU"),
    ("iVAPS-CycleSensitivity", "VCS"),
    ("iVAPS-FallTime", "IRL"),
    ("iVAPS-FallTimeEnable", "IRZ"),
    ("iVAPS-MaxExpiratoryPressure", "IMX"),
    ("iVAPS-MaxPressureSupport", "WPA"),
    ("iVAPS-MinExpiratoryPressure", "IMN"),
    ("iVAPS-MinPressureSupport", "WPM"),
    ("iVAPS-PatientHeight", "PHT"),
    ("iVAPS-RiseTime", "IRT"),
    ("iVAPS-RiseTimeEnable", "IRC"),
    ("iVAPS-SetMaxInspiratoryTime", "IVX"),
    ("iVAPS-SetMinInspiratoryTime", "IVN"),
    ("iVAPS-StartPressure", "IVS"),
    ("iVAPS-TargetAlveolarVentilation", "ITV"),
    ("iVAPS-TargetExpiratoryPressure", "EPI"),
    ("iVAPS-TargetRespiratoryRate", "IBR"),
    ("iVAPS-TriggerSensitivity", "VTS"),
]


REGISTRIES = {
    "vars":     (VAR_NAMES,                   "variable names (for `get` / `set`)"),
    "subtrees": (sorted(VAR_SUBTREES, key=str.lower),
                 "aggregate `get` targets (whole-subtree names, verified)"),
#    "reserved": (VAR_RESERVED,               "reserved `_NAME` specials"),
    "streams":  (STREAM_DATA_IDS,            "stream data IDs (for `stream --data-ids`)"),
    "events":   (EVENT_IDS,                  "event IDs (for `subscribe --events`)"),
    "spools":   (SPOOL_TYPES,                "spool types (for `spool`)"),
}

# Therapy-mode prefixes: `known vars cpap` -> Cpap-* (exact prefix match).
VAR_MODE_PREFIXES = {
    "cpap": "Cpap-", "autoset": "AutoSet-", "herauto": "HerAuto-",
    "asv": "ASV-", "asvauto": "ASVAuto-", "vauto": "VAuto-",
    "ivaps": "iVAPS-", "st": "ST-", "spont": "Spont-",
    "timed": "Timed-", "pac": "PAC-",
}

# Topic groups: `known vars summary` -> case-insensitive substring match.
VAR_TOPIC_KEYWORDS = {
    "summary":    ("summary",),
    "alarm":      ("alarm",),
    "ramp":       ("ramp",),
    "humidifier": ("humidifier",),
    "tube":       ("tube",),
    "reminder":   ("reminder",),
    "cellular":   ("cellular", "imei", "imsi", "sim", "accesspoint"),
    "bluetooth":  ("bluetooth",),
    "identifier": ("identifier", "serialnumber", "productcode", "productname"),
    "learn":      ("learn",),
    "streaming":  ("-50hz", "-100hz", "-twosecond", "-oneminute", "-estimated"),
}



def filter_vars(pat: str) -> list[tuple[str, str]]:
    """Group-aware filtering over (name, tag) pairs. Falls back to substring."""
    key = pat.lower()
    if key in VAR_MODE_PREFIXES:
        prefix = VAR_MODE_PREFIXES[key]
        return [(n, t) for n, t in VAR_NAMES if n.startswith(prefix)]
    if key in VAR_TOPIC_KEYWORDS:
        keywords = VAR_TOPIC_KEYWORDS[key]
        return [(n, t) for n, t in VAR_NAMES
                if any(k in n.lower() for k in keywords)]
    # substring match against either the long name or the _TAG short form
    return [(n, t) for n, t in VAR_NAMES
            if key in n.lower() or key in f"_{t}".lower()]


def var_groups_summary() -> None:
    print("therapy modes (exact prefix):")
    for key, prefix in sorted(VAR_MODE_PREFIXES.items()):
        n = sum(1 for name, _ in VAR_NAMES if name.startswith(prefix))
        print(f"  {key:<10}  {prefix:<10}  {n:3d}")
    print()
    print("topics (substring):")
    for key, keywords in sorted(VAR_TOPIC_KEYWORDS.items()):
        n = sum(1 for name, _ in VAR_NAMES
                if any(k in name.lower() for k in keywords))
        hint = ", ".join(keywords)
        print(f"  {key:<10}  {n:3d}  ({hint})")
    print()
    print("firmware subtree groups (for `get --group`):")
    non_empty = [(g, v) for g, v in VAR_GROUPS.items() if v]
    for g, v in sorted(non_empty, key=lambda x: -len(x[1])):
        print(f"  {g:<24s}  {len(v):3d}")
    print()


def print_var_pairs(pairs: list[tuple[str, str]]) -> None:
    """Two-column output: long name left, _TAG right."""
    if not pairs:
        return
    width = max(len(n) for n, _ in pairs)
    for name, tag in sorted(pairs):
        print(f"{name:<{width}}  _{tag}")
